name: 'C++ CI'

on:
  push:
    branches:
      - main
      - feature/11-outer-join
    tags:
      - 'v*'
  pull_request:
    branches:
      - main
      - feature/11-outer-join

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write  # для push
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive
          fetch-depth: 0
      
      - name: Update package manager
        run: sudo apt-get update

      - name: Install dependencies
        run: sudo apt-get install -y build-essential cmake libboost-test-dev libboost-system-dev libboost-thread-dev libsqlite3-dev

      - name: Configure CMake
        run: cmake -B build -S . -DPATCH_VERSION=${{ github.run_number }} -DENABLE_BOOST_TEST=ON -DENABLE_GOOGLE_TEST=ON
      
      - name: Build project
        run: cmake --build build -j$(nproc)
      
      - name: Run tests
        run: cmake --build build --target test
      
      - name: Build package
        run: cmake --build build --target package
      
      - name: Create or Update Release
        if: startsWith(github.ref, 'refs/tags/')
        uses: ncipollo/release-action@v1
        with:
          tag: ${{ github.ref_name }}
          name: Release ${{ github.ref_name }}
          artifacts: build/*.deb
          artifactErrorsFailBuild: true
          allowUpdates: true
          replacesArtifacts: true