name: 'C++ CI'

on:
  push:
    branches:
      - feature/3-allocator

    tags:
      - 'v*'

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write  # для push
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive
          fetch-depth: 0
      
      - name: Update package manager
        run: sudo apt-get update

      - name: Install dependencies
        run: sudo apt-get install -y build-essential cmake libboost-test-dev

      - name: Configure CMake
        run: cmake -B build -S . -DPATCH_VERSION=${{ github.run_number }} -DENABLE_BOOST_TEST=ON -DENABLE_GOOGLE_TEST=ON
      
      - name: Build project
        run: cmake --build build -j$(nproc)
      
      - name: Run tests
        run: cmake --build build --target test
      
      - name: Build package
        run: cmake --build build --target package
      
      - name: Create Release
        if: startsWith(github.ref, 'refs/tags/')  # Create release only for tags
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref_name }}
          release_name: Release ${{ github.ref_name }}
          draft: false
          prerelease: false
          
      - name: Upload Release Asset
        if: startsWith(github.ref, 'refs/tags/')  # Upload release asset only for tags
        id: upload-release-asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: build/helloworld-0.0.${{ github.run_number }}-Linux.deb
          asset_name: helloworld-0.0.${{ github.run_number }}-Linux.deb
          asset_content_type: application/vnd.debian.binary-package